[theme]
primaryColor="#F48FB1"
backgroundColor="#FFF9C4"
secondaryBackgroundColor="#F8BBD0"
textColor="#2c2c2c"
font="sans serif"

[server]
headless = true
port = $PORT
enableCORS = false

[browser]
gatherUsageStats = false
